development:
  adapter: redis
  url: redis://127.0.0.1:6379/7

test:
  adapter: test
  #url: redis://127.0.0.1:6379/7


production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: AuctionMarketplace_production
